//
// BrandedFoodObjectNutrients.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** An object containing nutrient information from multiple sources */
public struct BrandedFoodObjectNutrients: Codable {


    /** An array containing an object for each nutrient data point */
    public var chomp: [BrandedFoodObjectNutrientsChomp]?

    /** An array containing an object for each nutrient data point as found in the USDA database */
    public var usda: [BrandedFoodObjectNutrientsUsda]?
    public init(chomp: [BrandedFoodObjectNutrientsChomp]? = nil, usda: [BrandedFoodObjectNutrientsUsda]? = nil) { 
        self.chomp = chomp
        self.usda = usda
    }

}
