//
// BrandedFoodObjectPackage.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** An object containing basic packaging information about this item */
public struct BrandedFoodObjectPackage: Codable {


    /** Package quantity */
    public var quantity: Int?

    /** Package size */
    public var size: Int?
    public init(quantity: Int? = nil, size: Int? = nil) { 
        self.quantity = quantity
        self.size = size
    }

}
