//
// BrandedFoodObjectNutrientsChomp.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct BrandedFoodObjectNutrientsChomp: Codable {


    /** Nutrient name */
    public var name: String?

    /** The unit used for measure (e.g. if mesure is 3 tsp, the unit is tsp) */
    public var measurementUnit: String?

    /** Amount of the nutrient per 100g of food */
    public var per100g: BigDecimal?

    /** Nutrient value per serving */
    public var perServing: BigDecimal?

    /** Total nutrient value */
    public var total: BigDecimal?
    public init(name: String? = nil, measurementUnit: String? = nil, per100g: BigDecimal? = nil, perServing: BigDecimal? = nil, total: BigDecimal? = nil) { 
        self.name = name
        self.measurementUnit = measurementUnit
        self.per100g = per100g
        self.perServing = perServing
        self.total = total
    }
    public enum CodingKeys: String, CodingKey { 
        case name
        case measurementUnit = "measurement_unit"
        case per100g = "per_100g"
        case perServing = "per_serving"
        case total
    }

}
