//
// BrandedFoodObjectServing.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** An object containing serving information for this item */
public struct BrandedFoodObjectServing: Codable {


    public var chomp: BrandedFoodObjectServingChomp?

    public var usda: BrandedFoodObjectServingUsda?
    public init(chomp: BrandedFoodObjectServingChomp? = nil, usda: BrandedFoodObjectServingUsda? = nil) { 
        self.chomp = chomp
        self.usda = usda
    }

}
