//
// BrandedFoodObjectItems.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** An object containing information for this specific item. */
public struct BrandedFoodObjectItems: Codable {


    /** EAN/UPC barcode */
    public var barcode: String?

    /** Item name as provided by brand owner or as shown on packaging */
    public var name: String?

    /** The brand name that owns this item */
    public var brand: String?

    /** Ingredients in order of highest value to least */
    public var ingredients: String?

    public var package: BrandedFoodObjectPackage?

    public var serving: BrandedFoodObjectServing?

    public var categories: [String]?

    public var nutrients: BrandedFoodObjectNutrients?

    public var calorieConversionFactor: BrandedFoodObjectCalorieConversionFactor?

    /** The multiplication factor used to calculate protein from nitrogen */
    public var proteinConversionFactor: BigDecimal?

    public var dietLabels: BrandedFoodObjectDietLabels?

    /** An array of ingredient objects that were flagged while grading this item for compatibility with each diet */
    public var dietFlags: [BrandedFoodObjectDietFlags]?

    public var packagingPhotos: BrandedFoodObjectPackagingPhotos?

    /** An array of objects containing the constituent parts of a food (e.g. bone is a component of meat) */
    public var components: [BrandedFoodObjectComponents]?

    /** An array of objects containing information on discrete amounts of a food found in this item */
    public var portions: [BrandedFoodObjectPortions]?

    /** An array of ingredients in this item that may cause allergic reactions in people */
    public var allergens: [String]?

    /** An array of brands we have associated with this item. Some items are sold by more than 1 brand. */
    public var brandList: [String]?

    /** An array of countries where this item is sold */
    public var countries: [String]?

    public var countryDetails: BrandedFoodObjectCountryDetails?

    /** An array of ingredients made from palm oil */
    public var palmOilIngredients: [String]?

    /** An array of this item&#x27;s ingredients */
    public var ingredientList: [String]?

    /** A boolean indicating if we have English ingredients for this item */
    public var hasEnglishIngredients: Bool?

    /** An array of minerals that this item contains */
    public var minerals: [String]?

    /** An array of trace ingredients that may be found in this item */
    public var traces: [String]?

    /** An array of vitamins that are found in this item */
    public var vitamins: [String]?

    /** Common names associated with this item. These generally clarify what the item is (e.g. when the brand name is \&quot;BRAND&#x27;s Spicy Enchilada\&quot; the common name may be \&quot;Chicken enchilada\&quot;) */
    public var commonName: String?

    /** A description of this item */
    public var _description: String?

    /** An array of keywords that can be used to describe this item */
    public var keywords: [String]?

    /** Comments on any unusual aspects of this item. Examples might include unusual aspects of the food overall. */
    public var footnote: String?
    public init(barcode: String? = nil, name: String? = nil, brand: String? = nil, ingredients: String? = nil, package: BrandedFoodObjectPackage? = nil, serving: BrandedFoodObjectServing? = nil, categories: [String]? = nil, nutrients: BrandedFoodObjectNutrients? = nil, calorieConversionFactor: BrandedFoodObjectCalorieConversionFactor? = nil, proteinConversionFactor: BigDecimal? = nil, dietLabels: BrandedFoodObjectDietLabels? = nil, dietFlags: [BrandedFoodObjectDietFlags]? = nil, packagingPhotos: BrandedFoodObjectPackagingPhotos? = nil, components: [BrandedFoodObjectComponents]? = nil, portions: [BrandedFoodObjectPortions]? = nil, allergens: [String]? = nil, brandList: [String]? = nil, countries: [String]? = nil, countryDetails: BrandedFoodObjectCountryDetails? = nil, palmOilIngredients: [String]? = nil, ingredientList: [String]? = nil, hasEnglishIngredients: Bool? = nil, minerals: [String]? = nil, traces: [String]? = nil, vitamins: [String]? = nil, commonName: String? = nil, _description: String? = nil, keywords: [String]? = nil, footnote: String? = nil) { 
        self.barcode = barcode
        self.name = name
        self.brand = brand
        self.ingredients = ingredients
        self.package = package
        self.serving = serving
        self.categories = categories
        self.nutrients = nutrients
        self.calorieConversionFactor = calorieConversionFactor
        self.proteinConversionFactor = proteinConversionFactor
        self.dietLabels = dietLabels
        self.dietFlags = dietFlags
        self.packagingPhotos = packagingPhotos
        self.components = components
        self.portions = portions
        self.allergens = allergens
        self.brandList = brandList
        self.countries = countries
        self.countryDetails = countryDetails
        self.palmOilIngredients = palmOilIngredients
        self.ingredientList = ingredientList
        self.hasEnglishIngredients = hasEnglishIngredients
        self.minerals = minerals
        self.traces = traces
        self.vitamins = vitamins
        self.commonName = commonName
        self._description = _description
        self.keywords = keywords
        self.footnote = footnote
    }
    public enum CodingKeys: String, CodingKey { 
        case barcode
        case name
        case brand
        case ingredients
        case package
        case serving
        case categories
        case nutrients
        case calorieConversionFactor = "calorie_conversion_factor"
        case proteinConversionFactor = "protein_conversion_factor"
        case dietLabels = "diet_labels"
        case dietFlags = "diet_flags"
        case packagingPhotos = "packaging_photos"
        case components
        case portions
        case allergens
        case brandList = "brand_list"
        case countries
        case countryDetails = "country_details"
        case palmOilIngredients = "palm_oil_ingredients"
        case ingredientList = "ingredient_list"
        case hasEnglishIngredients = "has_english_ingredients"
        case minerals
        case traces
        case vitamins
        case commonName = "common_name"
        case _description = "description"
        case keywords
        case footnote
    }

}
